#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tilapia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tilapia")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTblProducto(TblProducto instance);
    partial void UpdateTblProducto(TblProducto instance);
    partial void DeleteTblProducto(TblProducto instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Tilapia.Properties.Settings.Default.TilapiaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TblProducto> TblProducto
		{
			get
			{
				return this.GetTable<TblProducto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblProducto")]
	public partial class TblProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _CodBarra;
		
		private string _NombreProd;
		
		private string _NombreCientifico;
		
		private System.Data.Linq.Binary _Imagen;
		
		private int _idPresentacion;
		
		private System.Nullable<int> _ExMinima;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCodBarraChanging(string value);
    partial void OnCodBarraChanged();
    partial void OnNombreProdChanging(string value);
    partial void OnNombreProdChanged();
    partial void OnNombreCientificoChanging(string value);
    partial void OnNombreCientificoChanged();
    partial void OnImagenChanging(System.Data.Linq.Binary value);
    partial void OnImagenChanged();
    partial void OnidPresentacionChanging(int value);
    partial void OnidPresentacionChanged();
    partial void OnExMinimaChanging(System.Nullable<int> value);
    partial void OnExMinimaChanged();
    #endregion
		
		public TblProducto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodBarra", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string CodBarra
		{
			get
			{
				return this._CodBarra;
			}
			set
			{
				if ((this._CodBarra != value))
				{
					this.OnCodBarraChanging(value);
					this.SendPropertyChanging();
					this._CodBarra = value;
					this.SendPropertyChanged("CodBarra");
					this.OnCodBarraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreProd
		{
			get
			{
				return this._NombreProd;
			}
			set
			{
				if ((this._NombreProd != value))
				{
					this.OnNombreProdChanging(value);
					this.SendPropertyChanging();
					this._NombreProd = value;
					this.SendPropertyChanged("NombreProd");
					this.OnNombreProdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCientifico", DbType="NVarChar(MAX)")]
		public string NombreCientifico
		{
			get
			{
				return this._NombreCientifico;
			}
			set
			{
				if ((this._NombreCientifico != value))
				{
					this.OnNombreCientificoChanging(value);
					this.SendPropertyChanging();
					this._NombreCientifico = value;
					this.SendPropertyChanged("NombreCientifico");
					this.OnNombreCientificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPresentacion", DbType="Int NOT NULL")]
		public int idPresentacion
		{
			get
			{
				return this._idPresentacion;
			}
			set
			{
				if ((this._idPresentacion != value))
				{
					this.OnidPresentacionChanging(value);
					this.SendPropertyChanging();
					this._idPresentacion = value;
					this.SendPropertyChanged("idPresentacion");
					this.OnidPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExMinima", DbType="Int")]
		public System.Nullable<int> ExMinima
		{
			get
			{
				return this._ExMinima;
			}
			set
			{
				if ((this._ExMinima != value))
				{
					this.OnExMinimaChanging(value);
					this.SendPropertyChanging();
					this._ExMinima = value;
					this.SendPropertyChanged("ExMinima");
					this.OnExMinimaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
